# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# 忽略引入库的所有警告
inhibit_all_warnings!

target 'QSKitLibrary_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'QSKitLibrary', :path => '../'

  # Pods for QuasiDemo, 按首字排序
  pod 'lottie-ios', '~> 4.2.0'
  pod 'RealmSwift', '~> 10.32.3'
  pod 'SDWebImage', '~> 5.15.8', :modular_headers => true
#  pod 'SDWebImageSVGKitPlugin', '~> 1.4.0'
  pod 'SDWebImageWebPCoder', '~> 0.11.0'
  #  pod 'SVProgressHUD', '~> 2.2.5'
  # 方便使用钥匙串
  pod 'SwiftKeychainWrapper', '~> 4.0.1'
  # 压缩解压缩文件目录
  pod 'Zip', '~> 2.1.2'
  # 仿微信图片选择器框架
  pod 'ZLPhotoBrowser', '~> 4.4.2'

end

target 'QSKitLibrary_Tests' do
  inherit! :search_paths

end

#---hooks---
$iOSVersion = '13.0'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Pod Architectures For Simulators
      # Needed for building for simulator on M1 Macs
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      # 避免pod中bundle target need sign
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      # Hook Pod target deployment version for xcode13
      if Gem::Version.new($iOSVersion) > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
      end
    end
  end
end
